version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - broker-kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    
    # cria pastas no diretório do projeto (atual do arquivo docker-compose), prevenindo mudanças que dependem do SO usado
    volumes:
      - ./data/zookeeper/data:/data 
      - ./data/zookeeper/datalog:/datalog 

  # propriedades de variáveis: https://docs.confluent.io/platform/current/kafka/multi-node.html
  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka1
    networks:
      - broker-kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    # mesma coisa do volume anterior
    volumes:
      - ./data/kafka1/data:/var/lib/kafka/data 

  # interface de controle do Kafka
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    networks:
      - broker-kafka
    depends_on:
      - kafka
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092

networks:
  broker-kafka:
    driver: bridge